name: CI
on:
  pull_request:
    branches: [ main, master ]
  push:
    tags: [ 'v*' ]
permissions:
  contents: write

jobs:
  dotnet35:
    uses: moth1995/ci-templates/.github/workflows/dotnet35-ci.yml@main
    with:
      sln_path: PES5_WE9_LE_CameraTool.sln
      app_project_dir: PES5_WE9_LE_CameraTool
      test_project_dir: PES5_WE9_LE_CameraTool.Tests
      test_assembly_name: PES5_WE9_LE_CameraTool.Tests.dll
      product_prefix: PES5_WE9_LE_CameraTool
      platforms_json: '["AnyCPU", "x86"]'
      tag_prefix: v
      run_tests: true
      enable_release: true
      retention_days: 7
